name: Alex's React Assistant
version: 0.0.4
schema: v1
models:
  # To see a list of your installed models, run `ollama list` in your terminal
  # Make sure the model name and tag are correct.
  - uses: continuedev/ollama
    with:
      model: codellama:latest
    override:
      roles:
        - chat
        - edit
  - uses: continuedev/ollama
    with:
      model: mistral:latest
    override:
      roles:
        - summarize
        - autocomplete
context:
  - uses: continuedev/code-context
  - uses: continuedev/docs-context
  - uses: continuedev/diff-context
  - uses: continuedev/terminal-context
  - uses: continuedev/problems-context
  - uses: continuedev/folder-context
  - uses: continuedev/codebase-context
rules:
  - uses: starter/react-rules
prompts:
  - uses: starter/test-prompt
docs:
  - uses: starter/react-docs
