name: Alex's React Assistant
version: 0.0.4
schema: v1
models:
  - name: gemma3 4b
    provider: ollama
    model: gemma3:4b
    apiBase: http://127.0.0.1:11434
  - name: llama3.1 8b
    provider: ollama
    model: llama3.1:8b
    apiBase: http://127.0.0.1:11434
context:
  - uses: continuedev/code-context
  - uses: continuedev/docs-context
  - uses: continuedev/diff-context
  - uses: continuedev/terminal-context
  - uses: continuedev/problems-context
  - uses: continuedev/folder-context
  - uses: continuedev/codebase-context
rules:
  - uses: starter/react-rules
prompts:
  - uses: starter/test-prompt
docs:
  - uses: starter/react-docs
